version: '3.7'

services:
    private-gpt:
        container_name: private-gpt
        build: .
        restart: always
        environment:
            $env_file: config.json

        volumes:
            - sshd:/etc/ssh/

        ports:
            - 22:22

volumes:
    sshd:
