version: '3.7'

services:
    private-gpt:
        container_name: private-gpt
        build: .
        restart: always
        environment:
            PERSIST_DIRECTORY: db
            MODEL_TYPE: GPT4All
            MODEL_PATH: models/ggml-gpt4all-j-v1.3-groovy.bin
            EMBEDDINGS_MODEL_NAME: all-MiniLM-L6-v2
            MODEL_N_CTX: 1000

        volumes:
            - sshd:/etc/ssh/

        ports:
            - 22:22

volumes:
    sshd:
